version: '3.3'

services:

  demo_data:
    container_name: demo_data
    build:
      context: demo_data
    volumes:
      - ./common/:/app/common
    env_file:
      - demo_data/.env

  running_ec2_instances:
    container_name: running_ec2_instances
    build:
      context: running_ec2_instances
    volumes:
      - ./common/:/app/common
    env_file:
      - running_ec2_instances/.env

  sqs_queue_messages:
    container_name: sqs_queue_messages
    build:
      context: sqs_queue_messages
    volumes:
      - ./common/:/app/common
    env_file:
      - sqs_queue_messages/.env

  current_aws_bill:
    container_name: current_aws_bill
    build:
      context: current_aws_bill
    volumes:
      - ./common/:/app/common
    env_file:
      - current_aws_bill/.env

  rds_data_api_query:
    container_name: rds_data_api_query
    build:
      context: rds_data_api_query
    volumes:
      - ./common/:/app/common
    env_file:
      - rds_data_api_query/.env

  web_scraped_value:
    container_name: web_scraped_value
    build:
      context: web_scraped_value
    volumes:
      - ./common/:/app/common
    env_file:
      - web_scraped_value/.env

  dynamodb_query:
    container_name: dynamodb_query
    build:
      context: dynamodb_query
    volumes:
      - ./common/:/app/common
    env_file:
      - dynamodb_query/.env

  open_pull_requests:
    container_name: open_pull_requests
    build:
      context: open_pull_requests
    volumes:
      - ./common/:/app/common
    env_file:
      - open_pull_requests/.env

  jira_issues:
    container_name: jira_issues
    build:
      context: jira_issues
    volumes:
      - ./common/:/app/common
    env_file:
      - jira_issues/.env.asim
